### PR TITLE
propose portal fixes

### PR DESCRIPTION
**Pull request by slorber**
Suggested changes for ios/android deployments, using the "docs only" mode: https://docusaurus.io/docs/docs-introduction#docs-only-mode

Related to https://github.com/facebook/docusaurus/discussions/6086

### CODE REVIEW

**Comment by slorber** [comment]
Not sure why it fails, can't access the logs 🤷‍♂️

**Comment by ptrhck** [comment]
Can you access the logs now?

Here are the logs otherwise:

```
Error: Docusaurus found broken links!
--
14:45:22.338 |  
14:45:22.338 | Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
14:45:22.338 | Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.
14:45:22.338 |  
14:45:22.338 | It looks like some of the broken links we found appear in many pages of your site.
14:45:22.338 | Maybe those broken links appear on all pages through your site layout?
14:45:22.339 | We recommend that you check your theme configuration for such links (particularly, theme navbar and footer).
14:45:22.339 | Frequent broken links are linking to:
14:45:22.339 | - /android/docs/intro
14:45:22.339 |  
14:45:22.339 |  
14:45:22.339 | Exhaustive list of all broken links found:
14:45:22.340 |  
14:45:22.340 | - On source page path = /android/404.html:
14:45:22.340 | -> linking to /android/docs/intro
14:45:22.340 |  
14:45:22.340 | - On source page path = /android/:
14:45:22.340 | -> linking to /android/docs/intro
14:45:22.340 |  
14:45:22.341 | - On source page path = /android/tutorial-basics/congratulations:
14:45:22.341 | -> linking to /android/docs/intro
14:45:22.341 |  
14:45:22.341 | - On source page path = /android/tutorial-basics/create-a-blog-post:
14:45:22.341 | -> linking to /android/docs/intro
14:45:22.341 |  
14:45:22.342 | - On source page path = /android/tutorial-basics/create-a-document:
14:45:22.342 | -> linking to /android/docs/intro
14:45:22.342 |  
14:45:22.342 | - On source page path = /android/tutorial-basics/create-a-page:
14:45:22.342 | -> linking to /android/docs/intro
14:45:22.342 |  
14:45:22.342 | - On source page path = /android/tutorial-basics/deploy-your-site:
14:45:22.343 | -> linking to /android/docs/intro
14:45:22.343 |  
14:45:22.343 | - On source page path = /android/tutorial-basics/markdown-features:
14:45:22.343 | -> linking to /android/docs/intro
14:45:22.343 |  
14:45:22.343 | - On source page path = /android/tutorial-extras/manage-docs-versions:
14:45:22.343 | -> linking to /android/docs/intro
14:45:22.343 |  
14:45:22.344 | - On source page path = /android/tutorial-extras/translate-your-site:
14:45:22.344 | -> linking to /android/docs/intro
```

**Comment by slorber** [comment]
Should now work, but your rewrites are hardcoded to the prod domain so it won't before merging 😅 

Note that as expected, the subdomain deployment does not work because it does not serve a `build` folder with a `ios` subfolder: 
- https://ios-portal-b1lykb6v1-ptrhck.vercel.app/ : can't work
- https://ios-portal-b1lykb6v1-ptrhck.vercel.app/ios : could eventually work if you configure it properly

**Comment by ptrhck** [comment]
Thanks for you contribution!

I would like to address two issues in a new PR:

1.  The navbar does not work as expected. When I am on `https://main-portal.vercel.app/ios` and click on `Android` it will route to `https://main-portal.vercel.app/ios/android`. Is this due to `_self `as suggsted in https://github.com/facebook/docusaurus/discussions/6086#discussioncomment-1839378 ? Should I use fully qualified URLs?
2. As mentioned in the discussion, I would like to make sure the preview deployments work. If I configure the build command to include `cp -R build ios/build`, I guess Vercel bot would still comment preview urls without the trailing subpath which would result in confusion for developers. The current config seems to work for the prod deployment, which is fine. Couldn't I just remove the `baseUrl `in the `docusaurus.config.js` if it is a preview deployment through Vercel envs?

**Comment by slorber** [comment]
Try using fully qualified urls in the navbar

I don't know Vercel enough to help much. If there's no way to provide a
custom deploy command per env, you can use "yarn build" and then create a
script to build according to current env variables

Note you can also tweak docu config according to env vars too, including
baseurl.

**Comment by ptrhck** [comment]
Check my https://github.com/ptrhck/docusaurus-portal/pull/3. It works as expected now: all preview deployments work for standalone previews and everything is accessible for the prod deployment from the main domain. Do you have any improvements to propose in this regard?

Only thing I could not resolve yet is the link in the very top left corner for the title and icon. I would like to route to the root domain from all dedicated deployments. When clicking on My Site from https://main-portal.vercel.app/ios to get to the landing page, but this routes to https://main-portal.vercel.app/ios as well.

**Comment by slorber** [comment]
Great, I don't think of any other improvement, but let me know if you see any other issue with this setup.


> Only thing I could not resolve yet is the link in the very top left corner for the title and icon.

navbar.logo.href should work

https://docusaurus.io/docs/next/api/themes/configuration#navbar-logo-href

**Pull request merged**
